### ISSUE TITLE
Consider publishing to Homebrew

### ISSUE THREAD

**Issue by donmccurdy** [magicien/GLTFQuickLook#1]
In the past I've discovered new QuickLook plugins from [this list](https://github.com/sindresorhus/quick-look-plugins), all of which are posted on Homebrew. Would be convenient to have a similar installation option here if that's feasible.

Thanks for this plugin! :)

**Comment by magicien** [comment]
Thank you for your suggestion!
I'll try to submit the plugin to Homebrew-Cask.

**Comment by magicien** [comment]
It seems that GLTFQuickLook is accepted as a Cask. caskroom/homebrew-cask#41186
Waiting for merger.

**Comment by donmccurdy** [comment]
Awesome! 😀 

One suggestion, it might be more consistent to name the cask `quicklook-gltf`: https://github.com/caskroom/homebrew-cask/search?utf8=%E2%9C%93&q=quicklook&type=

**Comment by magicien** [comment]
Thank you!
Cask name was automatically decided from the plugin name ([Generating a Token for the Cask](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#generating-a-token-for-the-cask)),
so I think gltfquicklook is ok.
There are some QL plugins which have the same naming like epubquicklook and webpquicklook.

**Comment by donmccurdy** [comment]
Great, thanks for publishing this!
