### ISSUE TITLE
issue installing on MacOS Sierra

### ISSUE THREAD

**Issue by jmlg10** [magicien/GLTFQuickLook#3]
Hello,

I've tried installing glTFQuicklook.qlgenerator on my mac, but it don't run.

trying debugging launching qlmanage by hand, I get this:

_#################
lvcpfriph0492:sample models goffjm$ qlmanage -p 'LV_Bronze.glb' 
Testing Quick Look preview with files:
LV_Bronze.glb
dyld: **warning, LC_RPATH @executable_path/../Frameworks in /Library/QuickLook/GLTFQuickLook.qlgenerator/Contents/MacOS/../Resources/GLTFSceneKit.framework/Versions/A/GLTFSceneKit being ignored in restricted program because of @executable_path**
2017-11-22 15:44:01.867 qlmanage[54241:3980021] -[SCNNode worldPosition]: unrecognized selector sent to instance 0x7f8d7efa2ef0
[ERROR] Computing 6571367.15831966 raised '-[SCNNode worldPosition]: unrecognized selector sent to instance 0x7f8d7efa2ef0'
2017-11-22 15:44:01.909 qlmanage[54241:3979988] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xa207, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-11-22 15:44:01.971 qlmanage[54241:3979988] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xcf3b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-11-22 15:44:01.972 qlmanage[54241:3979988] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xd303, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes_

**Comment by magicien** [comment]
Sorry, this plugin is available for macOS 10.13 (High Sierra) or later.
I will add the system requirement to README.md.

**Comment by donmccurdy** [comment]
It's working in Sierra (10.12.6) for me actually

**Comment by jmlg10** [comment]
Good news, but how did you install it?

regarding the log I get from my "terminal" what's wrong in my installation?

**Comment by donmccurdy** [comment]
The normal instructions just worked for me; not why sure sorry. 😐

**Comment by jmlg10** [comment]
Not for me..
May be for security reason in my corporate environment...(antivirus or something like that)

I should have to try on a more opened system at home...

**Comment by magicien** [comment]
SCNNode.worldPosition is defined at macOS 10.13 SceneKit.
I used it for centering a model on a thumbnail, but I don't think it affects previews.
The problem is that SceneKit changed behavior at macOS 10.13, and I optimized the code to High Sierra, so it might cause problems in Sierra.

The dyld warning is about GLTFSceneKit (Runpath Search Paths value). I think I can fix it, but this log doesn't affect this plugin.
I'm not sure about bootstrap_register errors... It might need sandboxing to stop the errors.

**Comment by jmlg10** [comment]
hello,

I've upgraded my Mac with High Sierra (10.13.1) and get the same issues...

May be it's because some security issues? how can I check ?

**Comment by jmlg10** [comment]
Now I get this running the command line 
$ qlmanage -d 1 -p 'LV_bronze.glb'

_[DEBUG] Preview test for LV_Bronze.glb -- file:///Users/goffjm/OneDrive_LV/OneDrive%20-%20Louis%20Vuitton%20Malletier/3D_Stuff/demo_files/glTF/Gltf_shared/sample%20models/. Content type UTI: dyn.ah62d4rv4ge80s5dc
[DEBUG] Previewing file:///Users/goffjm/OneDrive_LV/OneDrive%20-%20Louis%20Vuitton%20Malletier/3D_Stuff/demo_files/glTF/Gltf_shared/sample%20models/LV_Bronze.glb. Content type UTI: dyn.ah62d4rv4ge80s5dc. Generator used: <QLGenerator /Library/QuickLook/GLTFQuickLook.qlgenerator>
[DEBUG] Loading <QLGenerator /Library/QuickLook/GLTFQuickLook.qlgenerator>
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Library/QuickLook/GLTFQuickLook.qlgenerator/Contents/MacOS/../Resources/GLTFSceneKit.framework/Versions/A/GLTFSceneKit being ignored in restricted program because of @executable_path
[DEBUG] Previewing file:///Users/goffjm/OneDrive_LV/OneDrive%20-%20Louis%20Vuitton%20Malletier/3D_Stuff/demo_files/glTF/Gltf_shared/sample%20models/LV_Bronze.glb finished
[DEBUG] Thumbnailing LV_Bronze.glb -- file:///Users/goffjm/OneDrive_LV/OneDrive%20-%20Louis%20Vuitton%20Malletier/3D_Stuff/demo_files/glTF/Gltf_shared/sample%20models/ - type: dyn.ah62d4rv4ge80s5dc - generator: <QLGenerator /Library/QuickLook/GLTFQuickLook.qlgenerator> (try #1)
[DEBUG] Thumbnailing file:///Users/goffjm/OneDrive_LV/OneDrive%20-%20Louis%20Vuitton%20Malletier/3D_Stuff/demo_files/glTF/Gltf_shared/sample%20models/LV_Bronze.glb. Content type UTI: dyn.ah62d4rv4ge80s5dc. Generator used: <QLGenerator /Library/QuickLook/GLTFQuickLook.qlgenerator>
min: -1.000000 -0.994552 -0.198811 max: 1.000000 0.994552 0.198811
fov: 60.000000
camera: -0.000000 -0.000000 2.198811
[DEBUG] Thumbnailing file:///Users/goffjm/OneDrive_LV/OneDrive%20-%20Louis%20Vuitton%20Malletier/3D_Stuff/demo_files/glTF/Gltf_shared/sample%20models/LV_Bronze.glb finished
2017-11-23 16:25:39.875 qlmanage[3009:52578] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xb803, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-11-23 16:25:39.944 qlmanage[3009:52578] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xd93b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes._

Hence I get a window with the Preview Thumbnail (-p) or a window (-t) but the view is not dynamic...
Have you any ints?

**Comment by magicien** [comment]
It seems that the plugin failed to generate a preview and fell back to a thumbnail.
Can you upload the glb file?

**Comment by jmlg10** [comment]
here is the file, but I guess that the issue is somewhere else. I've tried with other files and get the same issue.
I guess that the issue is more in the installation, or in the configuration of my system.
Do I have to try opening a session as an "admin"

[LV_Bronze.zip](https://github.com/magicien/GLTFQuickLook/files/1501076/LV_Bronze.zip)

**Comment by magicien** [comment]
Hmm... I can see this model as a preview.
Could you please try these commands?
`mkdir /path/to/outputDir`
`qlmanage -o /path/to/outputDir -p LV_Bronze.glb`

It will output a scn file if the plugin works properly.

**Comment by jmlg10** [comment]
Ok, Done I get 2 files in the /path/outputDir
a Preview and PreviewProperties.plist but no windows with the scene open.
I get still an warning message in the terminal about LC_RPATH @executable_path...

**Comment by jmlg10** [comment]
@donmccurdy

How do you get this working on 10.12.6 MacOS (e.g. Sierra)?
I've tried at home on a personal mac(without any corporate security apps) and I can't achieved to make it working also...
Could it be linked to French location?

**Comment by magicien** [comment]
Can you see a preview for the generated scn file?
If not, please try this file: [LV_Bronze.glb.qlpreview.zip](https://github.com/magicien/GLTFQuickLook/files/1502688/LV_Bronze.glb.qlpreview.zip).

If you can't see a preview, something is wrong with SceneKit.qlgenerator.
It could be a compatibility problem between hardware and software.

**Comment by jmlg10** [comment]
How Am I suppose to open the Preview.scn file?
A Double click on it give no result.
An "Open with" "Apercu"(Preview app in French) don't give better results...

On the other hand the command:
 qlmanage -o /outputdir/ -p file.glb
Give a "Preview" file but without ".scn" as extension.

**Comment by magicien** [comment]
Select Preview.scn on Finder and push space key, and you can see the preview.

Can you upload LV_Bronze.glb.qlpreview directory and the command log of `qlmanage -o /outputdir/ -p file.glb`?

**Comment by jmlg10** [comment]
here is the log

_lvcpfriph0403:sample models goffjm$ qlmanage -o output -p 'LV_Bronze.glb' 
Testing Quick Look preview with files:
	LV_Bronze.glb
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Users/goffjm/Library/QuickLook/GLTFQuickLook.qlgenerator/Contents/MacOS/../Resources/GLTFSceneKit.framework/Versions/A/GLTFSceneKit being ignored in restricted program because of @executable_path
* /Users/goffjm/OneDrive_LV/OneDrive - Louis Vuitton Malletier/3D_Stuff/demo_files/glTF/Gltf_shared/sample models/LV_Bronze.glb produced a preview with data of type com.apple.scenekit.scene_

here is the an archive of the preview dir:
[LV_Bronze.glb.qlpreview.zip](https://github.com/magicien/GLTFQuickLook/files/1505060/LV_Bronze.glb.qlpreview.zip)

**Comment by jmlg10** [comment]
when I select your "Preview.scn" file and hit spacebar I get a window like this:
![screen shot 2017-11-27 at 09 06 54](https://user-images.githubusercontent.com/33903686/33256444-5e9860e4-d352-11e7-900f-0965cf267854.png)

**Comment by magicien** [comment]
I guess Verto Studio 3D tried to show the thumbnail and preview instead of SceneKit.qlpreview.

What GLTFQuickLook does is to convert gltf data into SceneKit data (.scn format) and pass the data to QuickLook service. By default, SceneKit data is handled by SceneKit.qlpreview, but it seems that Verto Studio 3D handles scn data on your mac.

I think you can see a preview with this command:
`qlmanage -g /System/Library/QuickLook/SceneKit.qlgenerator -c com.apple.scenekit.scene -p Preview.scn`

And you can check which QLGenerator is used for scn files with this command:
`qlmanage -d 1 -p Preview.scn`

By default, the command log looks like (SceneKit.qlgenerator is used):
> [DEBUG] Previewing file:///path/to/Preview.scn. Content type UTI: com.apple.scenekit.scene. Generator used: <QLGenerator /System/Library/QuickLook/SceneKit.qlgenerator>

**Comment by jmlg10** [comment]
I get this
lvcpfriph0403:LV_Bronze.glb.qlpreview goffjm$ qlmanage -g /System/Library/QuickLook/SceneKit.qlgenerator -c com.apple.scenekit.scene -p Preview.scn
Testing Quick Look preview with files:
	Preview.scn
	- force using content type UTI: com.apple.scenekit.scene
	- force using generator at path: /System/Library/QuickLook/SceneKit.qlgenerator
2017-11-27 16:15:43.447 qlmanage[78389:2585766] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9f03, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-11-27 16:15:43.531 qlmanage[78389:2585766] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xcc3b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.

**Comment by jmlg10** [comment]
I removed Verto Studio App, but still get the same

if I try the debug command, I get this
lvcpfriph0403:LV_Bronze.glb.qlpreview goffjm$ qlmanage -d 1 -p Preview.scn
Testing Quick Look preview with files:
	Preview.scn
[DEBUG] file:///Users/goffjm/Library/QuickLook/Toucan.qlgenerator/ might shadow a plug-in with the same identifier and version (<QLGenerator /Library/QuickLook/Toucan.qlgenerator>)
[DEBUG] file:///Users/goffjm/Library/QuickLook/Rhinoceros.qlgenerator/ might shadow a plug-in with the same identifier and version (<QLGenerator /Library/QuickLook/Rhinoceros.qlgenerator>)
[DEBUG] Preview test for Preview.scn -- file:///Users/goffjm/Desktop/glTF_quicklook/LV_Bronze.glb.qlpreview/. Content type UTI: dyn.ah62d4rv4ge81g25s
[DEBUG] file:///Users/goffjm/Library/QuickLook/iWork.qlgenerator/ is older than <QLGenerator /Library/QuickLook/iWork.qlgenerator>. Ignoring
[DEBUG] file:///Users/goffjm/Library/QuickLook/FreemindQL.qlgenerator/ might shadow a plug-in with the same identifier and version (<QLGenerator /Library/QuickLook/FreemindQL.qlgenerator>)
[DEBUG] file:///Users/goffjm/Library/QuickLook/VRED.qlgenerator/ might shadow a plug-in with the same identifier and version (<QLGenerator /Library/QuickLook/VRED.qlgenerator>)
[DEBUG] file:///Users/goffjm/Library/QuickLook/iBooksAuthor.qlgenerator/ might shadow a plug-in with the same identifier and version (<QLGenerator /Library/QuickLook/iBooksAuthor.qlgenerator>)
[DEBUG] No bundle document types in file:///Applications/DraftSight.app/Contents/Library/QuickLook/FxQuickLookDrawing.qlgenerator/
[DEBUG] file:///Applications/Fusion360.app/Contents/Libraries/Neutron/NQLGenerator.qlgenerator might shadow a plug-in with the same identifier and version (<QLGenerator /Applications/123D Design.app/Contents/Library/QuickLook/NQLGenerator.qlgenerator>)
[DEBUG] Previewing file:///Users/goffjm/Desktop/glTF_quicklook/LV_Bronze.glb.qlpreview/Preview.scn. Content type UTI: dyn.ah62d4rv4ge81g25s. Generator used: <QLGenerator /Applications/ID Util.app/Contents/Library/QuickLook/INDDpreviewer_1.1.8.qlgenerator>
[DEBUG] Loading <QLGenerator /Applications/ID Util.app/Contents/Library/QuickLook/INDDpreviewer_1.1.8.qlgenerator>
[DEBUG] Previewing file:///Users/goffjm/Desktop/glTF_quicklook/LV_Bronze.glb.qlpreview/Preview.scn did not produce anything
[DEBUG] Thumbnailing Preview.scn -- file:///Users/goffjm/Desktop/glTF_quicklook/LV_Bronze.glb.qlpreview/ - type: dyn.ah62d4rv4ge81g25s - generator: <QLGenerator /Applications/ID Util.app/Contents/Library/QuickLook/INDDpreviewer_1.1.8.qlgenerator> (try #1)
[DEBUG] Thumbnailing file:///Users/goffjm/Desktop/glTF_quicklook/LV_Bronze.glb.qlpreview/Preview.scn. Content type UTI: dyn.ah62d4rv4ge81g25s. Generator used: <QLGenerator /Applications/ID Util.app/Contents/Library/QuickLook/INDDpreviewer_1.1.8.qlgenerator>
[DEBUG] Thumbnailing file:///Users/goffjm/Desktop/glTF_quicklook/LV_Bronze.glb.qlpreview/Preview.scn did not produce anything
[WARNING] LSCopyDefaultApplicationURLForURL for Preview.scn -- file:///Users/goffjm/Desktop/glTF_quicklook/LV_Bronze.glb.qlpreview/ returned error Error Domain=NSOSStatusErrorDomain Code=-10814 "kLSApplicationNotFoundErr: E.g. no application claims the file"
2017-11-27 16:55:57.242 qlmanage[79073:2615411] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xae03, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-11-27 16:55:57.328 qlmanage[79073:2615411] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xdb3b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
^C[WARNING] Calling _Exit()

**Comment by magicien** [comment]
Did the "-g" option work for you?

According to the logs, ID Util.app tried to show a preview.

**Comment by jmlg10** [comment]
I'm afraid that "-g" fails also

goffjm$ qlmanage -g /System/Library/QuickLook/SceneKit.qlgenerator -c com.apple.scenekit.scene -p Preview.scn
Testing Quick Look preview with files:
	Preview.scn
	- force using content type UTI: com.apple.scenekit.scene
	- force using generator at path: /System/Library/QuickLook/SceneKit.qlgenerator
[WARNING] LSCopyDefaultApplicationURLForURL for Preview.scn -- file:///Users/goffjm/Desktop/glTF_quicklook/LV_Bronze.glb.qlpreview/ returned error Error Domain=NSOSStatusErrorDomain Code=-10814 "kLSApplicationNotFoundErr: E.g. no application claims the file"
2017-11-28 09:36:00.278 qlmanage[81241:2702061] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9d03, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-11-28 09:36:00.376 qlmanage[81241:2702061] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xc33b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.

May be I have better to give up, but I can't understand what happen on my system and why it works for you and for @donmccurdy (even on 10.12.6)...

I've "forced" the system to associate ".scn" files to Preview app.
It don't open as desired but I get  less errors

goffjm$ qlmanage -g /System/Library/QuickLook/SceneKit.qlgenerator -c com.apple.scenekit.scene -p Preview.scn
Testing Quick Look preview with files:
	Preview.scn
	- force using content type UTI: com.apple.scenekit.scene
	- force using generator at path: /System/Library/QuickLook/SceneKit.qlgenerator
2017-11-28 09:45:11.678 qlmanage[81780:2711342] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9b03, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-11-28 09:45:11.761 qlmanage[81780:2711342] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xc83b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.

I guess that the "permission denied" happen because of a non official app trying to open...
is there a way to "allow" it to run?

On another hand, is it normal that I don't have a directory "/include " in my "/usr/" directory?
so it's normal that _bootstrap_register_ process can't works

**Comment by jmlg10** [comment]
![screen shot 2017-11-28 at 10 51 52](https://user-images.githubusercontent.com/33903686/33313173-38382b86-d42a-11e7-813b-b314c1d77582.png)
I've installed Xcode, so I get the /Include folder but all is not clear, I get the preview only via command line.
Do I have to disable System Integrity Protection too? The worst is that even if all this manips can be made on my computer, I can't imagine doing this on all the Mac of the company...(and the IT dept neither)...
Have you a way to make installation "lighter" ?

**Comment by magicien** [comment]
It's weird that you had to install Xcode. I don't have /usr/include directory either.
I guess qlmanage command itself outputted 'Permission denied' logs. Whenever I use qlmanage command, I get 'Permission denied' logs even if it's a text file or an image file.

Could you please try [v0.2.1](https://github.com/magicien/GLTFQuickLook/releases/tag/v0.2.1)?
I changed some options for QuickLook API. I hope it changes something.

And can you get `qlmanage -m` command log? I would like to see the QL plugin list.

**Comment by jmlg10** [comment]
hey,

Yes, that's better, I now get this,
![screen shot 2017-11-29 at 12 33 08](https://user-images.githubusercontent.com/33903686/33373316-9c6d5be4-d501-11e7-8a19-638df96bcf98.png)
So, If I get the preview with Quicklook feature activated, is it normal I don't get the preview in "Cover Flow mode" ?

Anyway, as is, it's already cool...

Thanks for this, and sorry having boring you with my issues

JM

**Comment by jmlg10** [comment]
Sorry,
But if we consider this issue closed
Is it possible to delete this feed?
Thanks

**Comment by magicien** [comment]
Thank you for your cooperation!

> If I get the preview with Quicklook feature activated, is it normal I don't get the preview in "Cover Flow mode" ?
I'm not sure if it's normal, but it could happen.

Do you mean that you want to delete this issue? I can't delete your first comment, but I can make it empty and delete all other comments in this issue if you want.

**Comment by jmlg10** [comment]
Yes, that's the idea, I shall remove all unwanted informations in my first comment.
Thanks
Jmlg

**Comment by magicien** [comment]
Ok. Are you ready to delete?

**Comment by jmlg10** [comment]
Yes, on the other hand, I've got another issue after uninstalling the gltf-viewer of Bwasty (https://github.com/bwasty/gltf-viewer) I lose the PBR rendering in your quicklook viewer.
I don't know why, and what the installation of his app modifye the system. can you have a look?
Many Thanks

**Comment by magicien** [comment]
I have deleted some comments which have logs.

I don't think gltf-viewer affects QuickLook, because it is a stand-alone binary file.
I guess applications or other QuickLook plugins do something.

Can you get `qlmanage -m` command log?
Please make sure the log doesn't contain information which you don't want to send.

**Comment by jmlg10** [comment]
I understand, for me also it's quite strange. But on my system it happens. After installing/desinstallng glTF-viewer, your quicklook plug-in don't shows PBR rendering anymore.
I don't know how to recover it.
